//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetail
    {
        public string CardID { get; set; }
        public string UserName { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string VehicleNumber { get; set; }
        public string CardType { get; set; }
    }
}
