//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransaction
    {
        public string TransactionID { get; set; }
        public string Username { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Mode { get; set; }
        public string Name { get; set; }
        public string UserDescription { get; set; }
        public string AdminDescription { get; set; }
    }
}
